# Generated by Django 2.2.1 on 2019-05-21 18:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_remove_challenge_maxscore'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TestCases',
        ),
    ]
