# Generated by Django 2.2.1 on 2019-05-21 18:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_delete_testcases'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestCases',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('testcaseName', models.CharField(max_length=20, verbose_name='testcaseName')),
                ('explanation', models.TextField(verbose_name='explanation')),
                ('input', models.TextField(verbose_name='input')),
                ('output', models.TextField(verbose_name='output')),
                ('score', models.PositiveIntegerField(verbose_name='score')),
                ('challenge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.Challenge')),
            ],
        ),
    ]
