# Generated by Django 2.2.1 on 2019-05-21 18:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_testcases'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TestCases',
            new_name='TestCase',
        ),
    ]
