# Generated by Django 2.2.1 on 2019-05-23 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_challenge_score'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChallengeLeaderboard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=20, verbose_name='user')),
                ('contest', models.CharField(max_length=20, verbose_name='contest')),
                ('challenge', models.CharField(max_length=20, verbose_name='challenge')),
                ('status', models.CharField(max_length=20, verbose_name='status')),
                ('score', models.CharField(max_length=20, verbose_name='score')),
            ],
        ),
    ]
